### PR TITLE
Descriptor for zkSync Era Remix plugin.

### PR DESCRIPTION
**Pull request by stranger80**
We are adding a new Remix plugin to assist in development, compilation and deployment of Solidity smart contracts for zkSync Era ecosystem:

image

### CODE REVIEW

**Comment by yann300** [comment]
thanks @stranger80!
@LianaHus could you have a look at the plugin UX.

**Comment by stranger80** [comment]
> thanks @stranger80! @LianaHus could you have a look at the plugin UX.

Hello!
May I ask for feedback on this? Can we aim for the plugin launch today/tomorrow (6th-7th Dec)?

**Comment by yann300** [comment]
sorry for the dumb question but I need a bit of context.
zsync uses a specific version of the solidity compiler? can you point me to it?

**Comment by stranger80** [comment]
Hi @yann300 !

This plugin is using a zksolc compiler in the background (https://github.com/matter-labs/zksolc-bin) as per the description in https://era.zksync.io/docs/tools/compiler-toolchain/solidity.html . In fact, we use the HardHat wrapper for zksolc: https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-solc.html

**Comment by yann300** [comment]
Overall looks good. Could you have a look please @LianaHus ?
But the plugin doesn't seem to respond on theme changed
see remix

Also the dropdown may need to use bootstrap classes. Are you using bootstrap classes?

**Comment by stranger80** [comment]
I take the point on the themes, we are working to get this rectified, but we also very keen on publishing this as an early alpha for the users. This is also on the back of our other plugin - Starknet - which has caught substantial traction and generated quite some traffic. Do you think we can still publish the zkSync alpha, while we continue work on styling (which is expected to be refurbished significantly anyway).

**Comment by yann300** [comment]
ok let me check that with the others.
Also could you link to some doc or spec that would list the diff between zksolc and the normal one?

**Comment by yann300** [comment]
ok let me check that with the others.
Also could you link to some doc or spec that would list the diff between zksolc and the normal one?

**Comment by stranger80** [comment]
https://era.zksync.io/docs/tools/compiler-toolchain/overview.html
 https://github.com/code-423n4/2023-10-zksync/blob/main/docs/VM%20Section/How%20compiler%20works/overview.md
 https://era.zksync.io/docs/reference/architecture/differences-with-ethereum.html

Let me know if that is sufficient!

**Review by yann300 — APPROVED** [review]

**Comment by stranger80** [comment]
Thanks for merging! 
The plugin now also supports themes:
image

Will be implementing the same changes in the Starknet plugin shortly.

**Comment by JorikSchellekens** [comment]
We're reworking the plugins to look as follows:

image
image
image

**Pull request merged**
