### PR TITLE
Added Tenderly plugin

### PR DESCRIPTION
**Pull request by BogdanHabic**
As the title suggests, this PR adds the `profile.json` for the Tenderly plugin.

### CODE REVIEW

**Comment by bunsenstraat** [comment]
I deployed KityCore on Rinkeby 0x07A4baB49bBAD778b47dBd54684b594ec5fF0Bff
I pasted the address in the app, clicked verify, got an error
RemixClient.ts:81 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
So something there with the compilationresult is not going well. We should look at the data coming in. 

```
        Object.keys(result.data.contracts).forEach(key => {
            Object.keys(result.data.contracts[key]).forEach(nestedKey => {
                contractName = nestedKey;
                metadata = JSON.parse(result.data.contracts[key][nestedKey].metadata);
            })
        });
```

**Comment by BogdanHabic** [comment]
Hey @bunsenstraat, the issue was that the wrong contract was getting verified, due to the way the solc data was traversed).

[I've pushed out a fix](https://github.com/Tenderly/remix-tenderly/commit/1b4906eda301bd1d92c76139e70532971dc6d6f4) which lets the user pick which contract is getting verified. Keep in mind you might need to clear your local cache in order to get the new version served to you 😄

**Comment by bunsenstraat** [comment]
The verifier now works but there is not feedback on verification, only in the console I see stuff. Shouldn't there be feedback on success and error? For example, when I select the wrong contract there should be an error no? and so on. On success there is a contract on the tenderly page, could there be a link in the app to go there or something.

**Comment by BogdanHabic** [comment]
That does make sense, I'll add it to the app

**Comment by BogdanHabic** [comment]
Added the messages for both the [verification](https://github.com/Tenderly/remix-tenderly/commit/acba30d49b19983e562d4f64fe9eed6b69f930a9) and [import](https://github.com/Tenderly/remix-tenderly/commit/509a983c2e0d8bf514d8622514137bb711b46992) flows 😄

Again, keep in mind you might need to clear your local cache in order to get the new version served to you

**Comment by bunsenstraat** [comment]
two things:

1. if I verify with success and then change the address to something random and click verify again, the verification still returns success because it posts the first address to the call, not the updated one. So it seems the change in the address doesn't get updated in the state or something... please check this

2.best to remove the alert-link class for now I think because our dark theme messes it up
Screenshot 2020-12-29 at 14 53 28

**Comment by BogdanHabic** [comment]
Both changes have been incorporated.

**Comment by bunsenstraat** [comment]
all right, very cool, now one more, when you insert a wrong or correct API can you have some UI feedback there too? 👯  After that, I think it's fine.

**Comment by BogdanHabic** [comment]
Done 😉

**Review by bunsenstraat — APPROVED** [review]

**Pull request merged**
