### PR TITLE
Repoint Starknet plugin to new infrastructure

### PR DESCRIPTION
**Pull request by stranger80**
This change is to update the Starknet plugin descriptor to use the new (Prod) backend infrastructure - https://cairo-remix.nethermind.io.

### CODE REVIEW

**Comment by yann300** [comment]
@stranger80 somebody send us a report with this screenshot: https://discord.com/channels/725383452081389608/760790566333055006

is that somehow linked to this PR being merged?

**Comment by stranger80** [comment]
> @stranger80 somebody send us a report with this screenshot: https://media.discordapp.net/attachments/760790566333055006/1163349660870656010/2023-10-16_13.35.58.png?ex=653f40cd&is=652ccbcd&hm=3732792259483231365944f4cfdbe3c5f756eb97bcdf9617be4e17208b05786e&=&width=1386&height=214
> 
> is that somehow linked to this PR being merged?

No, this isn't caused by the PR. We had a backend service outage, this was also flagged to us by users via Telegram. Workaround is now in place, and we are working to deploy a proper resolution.

**Comment by yann300** [comment]
ok thanks for the prompt reply!

**Comment by ioedeveloper** [comment]
Screenshot 2023-10-17 at 14 24 53
Screenshot 2023-10-17 at 14 25 43

**Comment by ioedeveloper** [comment]
@stranger80 When i try to compile the hello-world file, i get the errors above.

**Comment by stranger80** [comment]
Hi @ioedeveloper, thank you for reaching out. 

Please note that the error message you quoted indicates that your workspace requires a feature available starting from Cairo 2.3.0-rc0, whereas the plugin includes Cairo 2.2.0 (the latest stable) compiler.

Also, please note this GitHub project is the generic Remix repo, whereas a better place to report the (suspected) issues in the Starknet plugin is the Starknet plugin repo (https://github.com/NethermindEth/starknet-remix-plugin).

I hope this helps.

**Pull request merged**
