### PR TITLE
Updating sourcify plugin to new version

### PR DESCRIPTION
**Pull request by edisinovcic**
Resolves: https://github.com/ethereum/sourcify/issues/197

### CODE REVIEW

**Comment by edisinovcic** [comment]
@yann300 @LianaHus this should fix the icon and name. Although the current logo may not be compatible with dark/light themes. Is there an option to load different icon for different themes or something like that?

**Comment by yann300** [comment]
ok thanks, ipfs hash is the same?

**Comment by edisinovcic** [comment]
> ok thanks, ipfs hash is the same?

Ofc not :)

Updated now.

By the way can you check that plugin can be loaded from ipfs and that it's on komputing. 

Providing a screenshot of the request inside Remix on the right.

ipfs_not_working_remix

**Comment by yann300** [comment]
the request URL seems wrong here.. it doesn't contain the ipfs hash

**Comment by edisinovcic** [comment]
@ryestew do you think something else needs to be updated?

**Comment by edisinovcic** [comment]
@yann300 tested and ready to be merged.

**Pull request merged**
