### PR TITLE
add sol2uml plugin

### PR DESCRIPTION
**Pull request by aquiladev**

### CODE REVIEW

**Comment by bunsenstraat** [comment]
There are some 404's

Screenshot 2020-12-29 at 07 56 23

**Comment by aquiladev** [comment]
it seems ipfs node does not work anymore, let me re-upload to another one

**Comment by bunsenstraat** [comment]
Did you get that to work?

**Comment by aquiladev** [comment]
not yet, I tested the plugin and it does not work as expected, meanwhile it works fine locally. I'll let you know when it fixed

**Comment by aquiladev** [comment]
this version should be good to go

**Comment by bunsenstraat** [comment]
I'm having trouble loading those files, how are you uploading that to IPFS? could be my mistake.

**Comment by aquiladev** [comment]
I use cloudflare gateway for testing https://cloudflare-ipfs.com/ipfs/Qmba4QdLvg9eemWPmQRLgH9ckLVPp7rhZAGi6McHXzQpW4/

**Review by bunsenstraat — CHANGES_REQUESTED** [review]
Awaiting some UI.

**Comment by aquiladev** [comment]
@bunsenstraat the latest version has a simple UI, I think it should be enough. Could you check?

**Comment by bunsenstraat** [comment]
> @bunsenstraat the latest version has a simple UI, I think it should be enough. Could you check?

I've added some more. If you allow me.
https://github.com/aquiladev/remix-sol2uml/pull/1

**Review by bunsenstraat — APPROVED** [review]

**Pull request merged**
