### PR TITLE
rm common api

### PR DESCRIPTION
**Pull request by bunsenstraat**

### CODE REVIEW

**Review by yann300 — APPROVED** [review]

**Review by luckykaunglay — COMMENTED** [review]
common-api/compiler/api.ts

**Comment by luckykaunglay** [comment]
common-api/compiler/api.ts

**Comment by luckykaunglay** [comment]
common-api/compiler/api.ts

**Comment by luckykaunglay** [comment]
Good

**Comment by luckykaunglay** [comment]
common-api/compiler/api.ts

**Comment by luckykaunglay** [comment]
Nice

**Pull request merged**
