### PR TITLE
Update profile.json

### PR DESCRIPTION
**Pull request by bunsenstraat**

### CODE REVIEW

**Comment by ryestew** [comment]
The sorting is still a problem.  Well -to explain further - the 1st time I loaded the plugin - I didn't notice any problems with the sorting - so I refreshed the page and loaded the plugin again and got:
image

I had refreshed the page because 2 of the tutorials were with the caret down - so you could read the description.  I'm not sure if that was intentional and I'm not sure if that is a bad thing.  So I reloaded the page just to see if it would load with those tutorials open.

**Comment by ryestew** [comment]
But when I reimport the repo it looks fine.
image

**Comment by ryestew** [comment]
I assume that the problem I had on the comment from 31 minutes ago was just caching (2 comments up).  I haven't been able to recreate it...yet.

I tried the solidity intro tutorial to see how testing was working.  I think there is a scrolling issue:
The 1st time I ran a test - it took a while and then errored and said the test didn't run. (I'm not sure this is an issue or not).  Then I ran it again and the test ran.  After running the test - it takes me to the top of that page - but the test result is at the bottom of the page.  I had forgotten I had scrolled to the bottom originally - so I didn't see the response -and I thought it hadn't run.  So I think this should be fixed.

**Comment by bunsenstraat** [comment]
> I had refreshed the page because 2 of the tutorials were with the caret down - so you could read the description. I'm not sure if that was intentional and I'm not sure if that is a bad thing. So I reloaded the page just to see if it would load with those tutorials open.

carets are in the app 'state' they will reopen to their previous state.

**Comment by bunsenstraat** [comment]
> I assume that the problem I had on the comment from 31 minutes ago was just caching (2 comments up). I haven't been able to recreate it...yet.
> 
> I tried the solidity intro tutorial to see how testing was working. I think there is a scrolling issue:
> The 1st time I ran a test - it took a while and then errored and said the test didn't run. (I'm not sure this is an issue or not). Then I ran it again and the test ran. After running the test - it takes me to the top of that page - but the test result is at the bottom of the page. I had forgotten I had scrolled to the bottom originally - so I didn't see the response -and I thought it hadn't run. So I think this should be fixed.

I can't reproduce this behavior. I need to see exactly what you're doing.

**Pull request merged**
