### PR TITLE
Updating sourcify to version 0.6.0-beta

### PR DESCRIPTION
**Pull request by edisinovcic**

### CODE REVIEW

**Comment by yann300** [comment]
This probably won't work with the current remix IDE, we need to integrate it with remix plugin 0.3 first

**Comment by bunsenstraat** [comment]
should this be merged or not?

**Comment by yann300** [comment]
not now, we first have release remix plugin with 0.3

**Comment by edisinovcic** [comment]
Yes, will convert to draft.

**Comment by yann300** [comment]
I think this can be merged now as we've updated remix ide @bunsenstraat @edisinovcic

**Comment by FabijanC** [comment]
I've just pushed changes that fix fetching contracts from Sourcify (both metadata and sources).

**Comment by edisinovcic** [comment]
@yann300 this should fix the fetching issue.

**Comment by bunsenstraat** [comment]
Please provide a documentation link, tnx

**Comment by FabijanC** [comment]
@bunsenstraat Thanks for the correction. I guess I was using an old version of the profile.json generation script that didn't require the documentation link.

**Review by bunsenstraat — APPROVED** [review]

**Pull request merged**
