### PR TITLE
Add ChainLens plugin

### PR DESCRIPTION
**Pull request by loredanacirstea**

### CODE REVIEW

**Comment by yann300** [comment]
It is available in remix-alpha, it looks like the bootstrap CSS is not applied, could that be an issue with the remix-plugin lib?

**Comment by loredanacirstea** [comment]
@yann300, I did not use bootstrap on my side. I still have to work on the css, but for me, remix-alpha displays ChainLens as exected. Though I see the base64 icon is not showing., so I will take a look.

**Comment by yann300** [comment]
Remix plugin injects in the iframe the css theme used by the ide, so the look and feel will be improved if you use bootstrap css classes in your code.
For the icon , might be an issue with the remix tabs, let us know...

**Comment by loredanacirstea** [comment]
@yann300 , I saw the css issue: the width & height of the available space was not properly detected in the iframe, so the column dimensions were not calculated correctly -> some content was not shown unless the window was resized somehow (which I probably did when I tested it). I was using the `Dimensions` API from the web version on React Native. I have a fallback in place now and it works.

**Pull request merged**
