### PR TITLE
Add solhint to list of plugins

### PR DESCRIPTION
**Pull request by fvictorio**
Hi, we've been working on a basic version of a remix plugin for solhint.

This leverages the new feature of multi-highlihgting, so I think it only works in the alpha version (for now). It also shows a list of errors for the last saved file in the side panel.

We hope we can continue to add features to this. For example, we'd love to be able to show the error message in a tooltip, but I think the IDE doesn't support that right now.

### CODE REVIEW

**Comment by yann300** [comment]
Thanks for this, that's great add! ;)

you can also use this API https://github.com/ethereum/remix-plugin#status to update the status of the plugin.
It's really nice to use it with `autocompile` true, but perhaps there could an option to turn it off (but keeping the plugin activated though).

**Comment by yann300** [comment]
I tried some basic code and that seems to work in remix.ethereum.org (the only thing is that it 's not possible to highlight 2 lines at the same time), how is that impacting the plugin? could you give me an example of code that breaks in remix.ethereum.org . 
Trying to see if that can be merged now or if we have to wait for a remix release.

**Comment by fvictorio** [comment]
Yeah, it works, the only problem is that it only highlights the last error. It shouldn't cause any issues though.

**Comment by yann300** [comment]
> For example, we'd love to be able to show the error message in a tooltip, but I think the IDE doesn't support that right now.

That is not supported, please feel free to open an issue in https://github.com/ethereum/remix-ide

**Pull request merged**
